export const USER_CREATED = 'USER_CREATED';
export const USER_ACTIVATED = 'USER_ACTIVATED';
export const INACTIVE_USER_SIGNED_IN = 'INACTIVE_USER_SIGNED_IN';

export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_STARTED = 'PASSWORD_RESET_STARTED';

export const EMAIL_RESET_STARTED = 'EMAIL_RESET_STARTED';
